### PR TITLE
Add preformatted cell type

### PR DESCRIPTION
**Pull request by vitPinchuk**
Resolves: #174

### CODE REVIEW

**Review by asimonok — CHANGES_REQUESTED** [review]
Please add an example of using preformatted cell type

**Review by asimonok — APPROVED** [review]
Looks good!

@mikhail-vl ready for review

**Review by mikhail-vl — CHANGES_REQUESTED** [review]
@vitPinchuk Please resolve conflicts.

**Review by mikhail-vl — APPROVED** [review]
Looks great!

**Pull request merged**
